### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: org.apache.felix.scr.impl.parser.ParseException: Exception during parsing

### ISSUE THREAD

**Issue by kwin** [jsedding/osgi-ds-metatype-diff#8]
When comparing the latest master build of acs-aem-commons with the last release via 
`java -jar ./osgi-ds-metatype-diff-0.0.1-SNAPSHOT.jar acs-aem-commons-bundle-3.19.0.jar acs-aem-commons-bundle-3.19.1-SNAPSHOT.jar` I get the following exception

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
05.02.2019 16:49:21 *ERROR* Missing element AD in element OCD
05.02.2019 16:49:21 *ERROR* Missing element AD in element OCD
05.02.2019 16:49:21 *ERROR* Missing element AD in element OCD
05.02.2019 16:49:21 *ERROR* Missing element AD in element OCD
05.02.2019 16:49:21 *ERROR* Missing element AD in element OCD
Exception in thread "main" java.lang.RuntimeException: org.apache.felix.scr.impl.parser.ParseException: Exception during parsing
	at net.distilledcode.tools.osgi.DeclarativeServices.lambda$toComponentMetadata$3(DeclarativeServices.java:60)
	at java.util.function.Function.lambda$andThen$1(Function.java:88)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at net.distilledcode.tools.osgi.DeclarativeServices.readComponentMetadata(DeclarativeServices.java:42)
	at net.distilledcode.tools.osgi.MetadataDiff$BundleMetadata.<init>(MetadataDiff.java:68)
	at net.distilledcode.tools.osgi.MetadataDiff.diff(MetadataDiff.java:33)
	at net.distilledcode.tools.osgi.MetadataDiff.main(MetadataDiff.java:28)
Caused by: org.apache.felix.scr.impl.parser.ParseException: Exception during parsing
	at org.apache.felix.scr.impl.xml.XmlHandler.startElement(XmlHandler.java:439)
	at org.apache.felix.scr.impl.parser.KXml2SAXParser.parseXML(KXml2SAXParser.java:76)
	at net.distilledcode.tools.osgi.DeclarativeServices.lambda$toComponentMetadata$3(DeclarativeServices.java:57)
	... 13 more
Caused by: org.apache.felix.scr.impl.parser.ParseException: Missing bundle entry sling.servlet.paths=/bin/wcm/contentfinder/qb/view
	at org.apache.felix.scr.impl.xml.XmlHandler.readPropertiesEntry(XmlHandler.java:552)
	at org.apache.felix.scr.impl.xml.XmlHandler.startElement(XmlHandler.java:346)
	... 15 more
```

**Comment by kwin** [comment]
At least the exception message should be improved so that it is clear in which file of which jar file the parsing exception occurs. 

I tried to come up with a refactoring which relies on a `BiFunction` taking the input stream and a name as return value for `DeclarativeServices.toComponentMetadata` but don't know how to properly call that within `DeclarativeServices.readComponentMetadata()`.

I am not that used to lambda programming. @jsedding Maybe you have a quick fix to at least expose the affected file name in the exception?

**Comment by jsedding** [comment]
@kwin Thanks for reporting. I pushed a commit that improves the error message.

FYI: In the example you posted it turned out that the `QueryBuilderViewHandler` component used the component annotation's `properties` field instead of the `property` field. The former causes the parser to look for a properties file in the bundle, which obviously fails.

**Comment by kwin** [comment]
@jsedding Thanks a lot for the quick fix! Just for the record, I reported the incorrect annotation for acs-aem-commons in https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1744.
